jfinkels/flask-restless

flask_restless/helpers.py, tests/helpers.py, tests/test_manager.py
Implementing enhancement #385. `include_methods` now works on non-callable properties.
=> Allow include methods on properties

docs/searchformat.rst, flask_restless/search.py, tests/test_search.py
- Solving issue https://github.com/jfinkels/flask-restless/issues/327
=> Fix for issue 327: order by relation

CHANGES, docs/basicusage.rst, flask_restless/manager.py, tests/helpers.py, tests/test_manager.py, tests/test_views.py
Before, the APIManager.init_app() method would store the Flask
application provided to it as `self.app`. This violates the rules for
approved Flask extensions, as it makes it impossible to initialize
multiple Flask applications in parallel.
This also fixes an issue with providing a session or Flask-SQLAlchemy
database object in the constructor of APIManager, and later initializing
the Flask application.
This fixes issues #313 and #389.
=> Makes init_app() no longer store a Flask app

CHANGES, docs/customizing.rst, flask_restless/manager.py, flask_restless/search.py, flask_restless/views.py, tests/test_views.py
Introduces the `allow_delete_many` keyword argument to
`APIManager.create_api`, which indicates that requests to, for example,
`DELETE /api/person`, with optional search parameters in the `q` query
parameter, will bulk delete multiple instances of the Person model. This
mirrors the `allow_patch_many` behavior that already existed.
This fixes issue #237.
=> Allow bulk deletion of model instances.

docs/requestformat.rst
The returned code on a successful 'PATCH_MANY' query is 200, not 201.
=> Fix response HTTP code for PATCH many in docs

flask_restless/manager.py, tests/test_manager.py
Hi!
The subject of pull-request is similar to #226, but I choose another realization: APIManager uses a delayed initialization if the app isn't set yet. So we can keep logic of naming blueprints. The implementation's idea is used by other flask extensions such as flask-admin and flask-restful.
Thanks for the great extension!
=> Removes a mandatory dependency on the Flask app.

flask_restless/manager.py
Model classes that have been defined in a declarative style are not guaranteed to have a `__tablename__` attribute.  For example, if they have been declared in a hybrid style with an embedded table:
class example(base):
__table__ = Table(...)
However even those declared just via a `__tablename_` will have a `__table__` attribute (created by the metaclass), so to infer the collection name in all cases we should use `__table__.name`.
=> Infer collection_name from __table__

CHANGES, docs/api.rst, docs/customizing.rst, flask_restless/__init__.py, flask_restless/helpers.py, flask_restless/manager.py, flask_restless/serialization.py, flask_restless/views/base.py, flask_restless/views/resources.py, tests/test_creating.py, tests/test_fetching.py, tests/test_manager.py, tests/test_serialization.py
This fixes issues #440 and #475.
=> Adds per-model serialization

CHANGES, docs/api.rst, flask_restless/__init__.py, flask_restless/helpers.py, flask_restless/manager.py, flask_restless/serialization.py, flask_restless/views/base.py, tests/test_manager.py
Hey, here's my solution for #476. I hope it's acceptable. If I've forgotten anything please let me know!
All enabled tests are passing on the branch:
```
awalton@tgv:~/work/flask-restless:overriden_primary_key_in_links  V $ py.test           (restless)
======================================= test session starts ========================================
platform darwin -- Python 2.7.10, pytest-2.9.0, py-1.4.31, pluggy-0.3.1
rootdir: /Users/awalton/work/flask-restless, inifile:
collected 449 items
tests/test_bulk.py sssssss
tests/test_creating.py ..........................................ss..
tests/test_deleting.py s............
tests/test_fetching.py ............sss................................................s...
tests/test_filtering.py …
```
=> Fixes: #476 - Overriden primary key in links

flask_restless/search.py, tests/test_filtering.py, tests/test_jsonapi/test_fetching_data.py
When trying to fetch relationships via _/resource/<id>/relation_name/_ all existing resources of the relation type are returned. Not only those related to the resource.
I debugged this and I think that I found the potential bug.
The _filter()_ method returns a new query object which was thrown away.
Also, the "in" operator doesn't seem to work on _InstrumentedAttribute_. So I changed it to use the in_() method.
=> Fixes: Fetching relationships fetches all existing resources

requirements-test.txt, setup.py, tests/helpers.py, tests/test_bulk.py, tests/test_creating.py, tests/test_deleting.py, tests/test_fetching.py, tests/test_filtering.py, tests/test_jsonapi/test_server_responsibilities.py, tests/test_manager.py, tests/test_metadata.py, tests/test_updating.py, tests/test_validation.py
Commit 4b3cc1b0b122ccc5469a0257d72854623388d0aa, which removes nose-specific code, breaks the build for Python 2.6, since that version of Python doesn't have `unittest.skip()`, for example. Let's import `unittest2` instead and see what happens.
Testers should still be able to use nose, it's just not required anymore.
=> Replaces nose with unittest2

tests/test_filtering.py
This is a failing unit test that any solution to issue #435 must pass.
=> Adds failing unit test for using 'and' and 'or' with 'has' and 'any' in filters

CHANGES, docs/basicusage.rst, docs/conf.py, docs/databasesetup.rst, docs/index.rst, flask_restless/manager.py, flask_restless/serialization/__init__.py, flask_restless/serialization/deserializers.py, flask_restless/serialization/serializers.py, flask_restless/views/base.py, flask_restless/views/resources.py, tests/helpers.py, tests/test_jsonapi/test_updating_resources.py, tests/test_manager.py, tests/test_polymorphism.py
This commit adds support for fetching, creating, updating, and deleting
at endpoints corresponding to APIs created for polymorphic models
defined using single table inheritance.
This also changes the default serializer so that it supports
heterogeneous collections directly.
Fixes issue #200.
This is currently a work-in-progress: it needs documentation to explain what operations are supported. This could be an opportunity to create a special section of the documentation on "Association proxies, polymorphic tables, hybrid properties, etc."
=> Adds single table inheritance support for models

docs/api.rst, docs/basicusage.rst, docs/changelog.rst, docs/creating.rst, docs/deleting.rst, docs/fetching.rst, docs/processors.rst, docs/requestformat.rst, docs/serialization.rst, docs/updating.rst, docs/updatingrelationships.rst, examples/clients/jquery/__main__.py, examples/quickstart.py, examples/server_configurations/authentication/__main__.py, examples/server_configurations/custom_serialization.py, examples/server_configurations/separate_endpoints.py, flask_restless/__init__.py, flask_restless/manager.py, tests/helpers.py, tests/test_creating.py, tests/test_deleting.py, tests/test_fetching.py, tests/test_filtering.py, tests/test_jsonapi/test_server_responsibilities.py, tests/test_manager.py, tests/test_metadata.py, tests/test_serialization.py, tests/test_updating.py
Flask version 0.11 deprecates imports from `flask.ext.*` in favor import
from "flask_*" for Flask extensions. This commit changes references to,
among others, `flask.ext.restless` to `flask_restless`.
=> Replaces "flask.ext." with "flask_".

CHANGES, docs/databasesetup.rst, flask_restless/serialization/serializers.py, tests/test_polymorphism.py
This pull request supercedes pull request #546.
=> Adds support for joined table inheritance.

README
`nosetests` is no longer required. Based on the Python interpreter,
a `psycopg2` module has to be installed.
=> Fix instructions for running tests

CHANGES, flask_restless/helpers.py, flask_restless/serialization/deserializers.py, flask_restless/views/resources.py, tests/test_creating.py, tests/test_updating.py
This fixes issue #559 and supercedes pull request #561. The `strings_to_datetimes` helper function was left over from an earlier version and was unnecessary. The checks for an attribute being `type` or `links` were pointless, because the `strings_to_datetimes` function was already only looking at the `attributes` dictionary of a resource object.
This commit includes unit tests for creating and updating a resource, and includes a changelog entry.
=> Allows attributes with JSON API "reserved" names.

CHANGES, docs/basicusage.rst, flask_restless/manager.py, flask_restless/serialization/serializers.py, tests/test_manager.py, tests/test_serialization.py
Fixes issue #540. Thanks to all those who helped with reporting and offering solutions.
=> Correctly support models without an "id" column

.travis.yml, CHANGES, tests/helpers.py
This adds to pull request #584 automated Travis tests using simplejson.
=> Add simplejson tests

tests/helpers.py
We should use the same branch here as Flask does in its json code. I
have verified the BetterJSONEncoder derivative to work with both
libraries.
This fixes #583.
=> Fix test suites failing with simplejson.

.travis.yml, requirements-test.txt, tests/test_filtering.py, tests/test_filtering_postgresql.py
This pull request removes the postgres testing from the other tests so that it is easier to skip if desired. This also removes the test dependency on `testing.postgresql` in favor of just creating the database in the Travis configuration directly (using the technique recommended by Travis itself).
=> Separates PostgreSQL testing from other tests

CHANGES, flask_restless/views/resources.py, tests/test_updating.py
This commit causes the server to give a clearer error message if the
resource ID given in the resource object on an update request is not a
string.
This fixes issue #534.
=> Give a clearer error message if id is not a string

CHANGES, docs/installation.rst, flask_restless/__init__.py, flask_restless/views/__init__.py, flask_restless/views/base.py, flask_restless/views/function.py, flask_restless/views/relationships.py, flask_restless/views/resources.py, requirements.txt, setup.py, tests/helpers.py, tests/test_creating.py, tests/test_jsonapi/test_server_responsibilities.py, tests/test_metadata.py, tests/test_server_responsibilities.py, tests/test_updating.py
This commit also eliminates mimerender as a dependency.
Fixes issue #479.
=> Removes duplicate Content-Type headers in response

docs/pagination.rst
"Anything but a positive integer" would mean, e.g., -1 or "foo" or an empty list. This is not true - the code requires both parameters to be a positive integer. The value 0 is the only value that disables pagination.
=> Fix documentation on pagination.

.travis.yml, docs/conf.py, docs/flaskstyle.sty
Removes some deprecated options for the LaTeX builder in Sphinx 1.5. Also corrects an incorrect reference to the logo file to make the LaTeX documentation build without error.
=> Removes Sphinx deprecated LaTeX options

CHANGES, docs/api.rst, docs/filtering.rst, flask_restless/__init__.py, flask_restless/search/__init__.py, flask_restless/search/operators.py, tests/test_filtering.py
Simpler version of pull request #590, which allows registering a custom operator for use in filtering. This pull request includes one test and user-facing documentation.
=> Allows registering a custom operator for filters

tests/test_fetching.py, tests/test_filtering.py
Tests corresponding to the situation described in issue #562.
=> Adds tests for filtering/sorting hybrid properties

docs/installation.rst
=> Marks Flask-SQLAlchemy as supported not required

CHANGES, flask_restless/serialization/deserializers.py, tests/test_jsonapi/test_creating_resources.py, tests/test_validation.py
This supersedes pull request #545 by making the changes I requested there. Making this change also revealed a bug in some unit tests.
=> Refactors deserializer code to make it more modular

flask_restless/views/base.py, tests/helpers.py, tests/test_fetching.py, tests/test_filtering.py, tests/test_jsonapi/test_fetching_data.py
Previously, Flask-Restless was not URL encoding the `first`, `last`,
`next`, and `prev` pagination links in the response JSON document. This
commit corrects that and additionally corrects some imprecise unit tests
that were not accounting for URL encoding.
Fixes issue #553.
=> URL encodes first, last, prev, and next links.

.travis.yml
In order to avoid having huge Travis build matrices, this pull request eliminates `simplejson` and `future` tests on Python 3, and tests only `future` on Python 2.7
=> Only test backport dependencies on Python 2

CHANGES, docs/sorting.rst, flask_restless/search/drivers.py, flask_restless/views/base.py, flask_restless/views/function.py, flask_restless/views/relationships.py, flask_restless/views/resources.py, tests/test_fetching.py
Partial fix for issue #626. This pull request allows the client to request case-insensitive sorting by setting the query parameter `ignorecase=1`. It does not create a server-side option to enable case-insensitive sorting by default. I plan on adding that in a new commit on this pull request.
=> Allows client to request case-insensitive sorting
